/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  admin: () => import("@/views/_admin/admin/index.vue"),
  system_role: () => import("@/views/_admin/system/role/index.vue"),
  system_user: () => import("@/views/_admin/system/user/index.vue"),
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  init: () => import("@/views/_builtin/init/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "social-callback": () => import("@/views/_builtin/social-callback/index.vue"),
  "user-center": () => import("@/views/_builtin/user-center/index.vue"),
  disk: () => import("@/views/_disk/disk/index.vue"),
  gateway: () => import("@/views/_gateway/gateway/index.vue"),
  server: () => import("@/views/_server/server/index.vue"),
};
