/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base$view.admin',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'disk',
    path: '/disk',
    component: 'layout.base$view.disk',
    meta: {
      title: 'disk',
      i18nKey: 'route.disk'
    }
  },
  {
    name: 'gateway',
    path: '/gateway',
    component: 'layout.base$view.gateway',
    meta: {
      title: 'gateway',
      i18nKey: 'route.gateway'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'init',
    path: '/init',
    component: 'layout.blank$view.init',
    meta: {
      title: 'init',
      i18nKey: 'route.init',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'server',
    path: '/server',
    component: 'layout.base$view.server',
    meta: {
      title: 'server',
      i18nKey: 'route.server'
    }
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.base$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback'
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:cloud-service-management',
      order: 2
    },
    children: [
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept',
          localIcon: 'menu-department',
          order: 4
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict',
          localIcon: 'menu-dict',
          order: 6
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          icon: 'mingcute:list-ordered-line',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice',
          icon: 'carbon:notification',
          order: 7
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post',
          localIcon: 'menu-post',
          order: 5
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          icon: 'carbon-user-role',
          order: 2
        }
      },
      {
        name: 'system_setting',
        path: '/system/setting',
        component: 'view.system_setting',
        meta: {
          title: 'system_setting',
          i18nKey: 'route.system_setting'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'carbon:user',
          order: 1
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center'
    }
  }
];
