/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base$view.admin',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      module: 'admin'
    }
  },
  {
    name: 'ai-key',
    path: '/ai-key',
    component: 'layout.base$view.ai-key',
    meta: {
      title: 'ai-key',
      i18nKey: 'route.ai-key',
      icon: 'mdi:key-variant',
      order: 8,
      module: 'gateway'
    }
  },
  {
    name: 'gateway',
    path: '/gateway',
    component: 'layout.base$view.gateway',
    meta: {
      title: 'gateway',
      i18nKey: 'route.gateway',
      icon: 'mdi:view-dashboard-outline',
      order: 7,
      module: 'gateway'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.blank$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'init',
    path: '/init',
    component: 'layout.blank$view.init',
    meta: {
      title: 'init',
      i18nKey: 'route.init',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log',
      localIcon: 'menu-log',
      order: 4,
      module: 'admin'
    },
    children: [
      {
        name: 'log_errorlog',
        path: '/log/errorlog',
        component: 'view.log_errorlog',
        meta: {
          title: 'log_errorlog',
          i18nKey: 'route.log_errorlog',
          icon: 'fluent:clipboard-error-24-regular',
          order: 3
        }
      },
      {
        name: 'log_loginlog',
        path: '/log/loginlog',
        component: 'view.log_loginlog',
        meta: {
          title: 'log_loginlog',
          i18nKey: 'route.log_loginlog',
          localIcon: 'menu-login_log',
          order: 1
        }
      },
      {
        name: 'log_operlog',
        path: '/log/operlog',
        component: 'view.log_operlog',
        meta: {
          title: 'log_operlog',
          i18nKey: 'route.log_operlog',
          localIcon: 'menu-operate_log',
          order: 2
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'models',
    path: '/models',
    component: 'layout.base',
    meta: {
      title: 'models',
      i18nKey: 'route.models',
      icon: 'mdi:brain',
      order: 9,
      module: 'gateway'
    },
    children: [
      {
        name: 'models_model',
        path: '/models/model',
        component: 'view.models_model',
        meta: {
          title: 'models_model',
          i18nKey: 'route.models_model'
        }
      },
      {
        name: 'models_provider',
        path: '/models/provider',
        component: 'view.models_provider',
        meta: {
          title: 'models_provider',
          i18nKey: 'route.models_provider'
        }
      }
    ]
  },
  {
    name: 'server',
    path: '/server',
    component: 'layout.base$view.server',
    meta: {
      title: 'server',
      i18nKey: 'route.server',
      module: 'server'
    }
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.base$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:cloud-service-management',
      order: 2,
      module: 'admin'
    },
    children: [
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept',
          localIcon: 'menu-department',
          order: 4
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict',
          icon: 'streamline-ultimate:book-open-bookmark',
          order: 6
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          icon: 'mingcute:list-ordered-line',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice',
          icon: 'carbon:notification',
          order: 7
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post',
          localIcon: 'menu-post',
          order: 5
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          icon: 'carbon-user-role',
          order: 2
        }
      },
      {
        name: 'system_setting',
        path: '/system/setting',
        component: 'view.system_setting',
        meta: {
          title: 'system_setting',
          i18nKey: 'route.system_setting',
          icon: 'carbon:settings',
          order: 8
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'carbon:user',
          order: 1
        }
      }
    ]
  },
  {
    name: 'timer',
    path: '/timer',
    component: 'layout.base$view.timer',
    meta: {
      title: 'timer',
      i18nKey: 'route.timer',
      icon: 'fluent:clock-24-regular',
      order: 3,
      module: 'admin'
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.auto$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
