# jwt configuration
jwt:
    signing-key: qmPlus
    expires-time: 7d
    buffer-time: 1d
    issuer: devops-admin

# autocode configuration
autocode:
    web: web/src
    root: "" # root 自动适配项目根目录, 请不要手动配置,他会在项目加载的时候识别出根路径
    server: server
    module: 'github.com/hllkk/devops-admin/server'
    ai-path: ""  # AI服务路径