"""前端 Upstream 同步工具模块"""

__all__ = [
    # git_ops
    'run_git',
    'get_current_branch',
    'get_branch_hash',
    'has_uncommitted_changes',
    'stash_changes',
    'stash_pop',
    'checkout_branch',
    'fetch_remote',
    'merge_branch',
    'push_branch',
    'get_conflict_files',
    'checkout_file_version',
    'add_files',
    'commit',
    'reset_hard',
    'get_diff_stat',
    'get_diff_files',
    'get_file_diff',
    # config
    'load_config',
    'save_config',
    'get_config',
    'set_config',
    'is_auto_accept_file',
    'get_frontend_dir',
    'get_log_dir',
    # ui
    'show_header',
    'show_main_menu',
    'show_config_menu',
    'show_message',
    'show_error',
    'show_success',
    'show_warning',
    'show_confirm',
    'show_spinner',
    'show_file_table',
    'show_preview_summary',
    'show_diff_preview',
    'ask_conflict_action',
    'ask_file_preview',
    'ask_rollback_record',
    # preview
    'show_upstream_preview',
    'preview_command',
    # conflict
    'handle_conflicts',
    'has_conflicts',
    # rollback
    'load_history',
    'save_history',
    'add_history_record',
    'create_sync_record',
    'show_sync_history',
    'rollback_sync',
    'rollback_command',
    'history_command',
]